### ISSUE TITLE
The function hash_script is not needed

### ISSUE THREAD

**Issue by XuJiandong** [ickb/v1-core#4]
https://docs.rs/ckb-gen-types/0.117.0/ckb_gen_types/packed/struct.Script.html#method.calc_script_hash

The `Script` has this function which enabled by default in ckb-std.

**Comment by phroi** [comment]
Good catch, that method came to `ckb-std` well after my implementation.

 I'll update the code with your suggestion, thanks!

**Comment by phroi** [comment]
See: https://github.com/nervosnetwork/capsule/issues/111
